### ISSUE TITLE
Doesn't compile on recent glibc (Arch Linux)

### ISSUE THREAD

**Issue by nyanpasu64** [yugr/libdebugme#3]
glibc 2.32 removed the sys_siglist variable which this project uses to lookup signal names. This results in the following build error on recent Linux distros:

```
src/debugme.c: In function ‘debugme_install_sighandlers’:
src/debugme.c:49:27: error: ‘sys_siglist’ undeclared (first use in this function)
   49 |     const char *signame = sys_siglist[sig];
      |                           ^~~~~~~~~~~
```

I'm not familiar with this issue, but it seems the same issue was reported in another project at https://github.com/greenbone/gvmd/issues/1279 and fixed in https://github.com/greenbone/gvmd/pull/1280 (replace `sys_siglist[sig]` with `strsignal(sig)`). The documentation for the removal of `sys_siglist` is in the [glibc 2.32 release notes](https://sourceware.org/pipermail/libc-announce/2020/000029.html) (2020-08).

I'll file a PR to fix this issue soon.

**Comment by yugr** [comment]
Hi, first of all thank you for your interest in libdebugme.

I believe lack of signal safety was the original reason why I didn't use `strsignal`... Glibc still exports this symbol in `.so` (just removed it from it's headers) so maybe we can get away with something like
```
extern const char *const sys_siglist[];
```
? Let me know if you don't have time to test this, I'll try it on weekend. Alternative solutions have disadvantages:
* `strsignal` is, as you noted in PR, technically unsafe
* precomputing signal names at program start (by calling `strsignal` for all signals and storing results in temp. array) will slow startup and waste memory

**Comment by yugr** [comment]
Could you check if this is fixed on trunk now?

**Comment by nyanpasu64** [comment]
Seems to build fine now. Catches a Python segfault as expected, doesn't catch a kdiff3 segfault, maybe because it invokes drkonqi's crash handler instead (which asks to file a bug report, rather than allowing you to debug the crash yourself).

Are you confident that sys_siglist will not be removed entirely (or its functionality broken) in future glibc?

**Comment by yugr** [comment]
Removing it would mean that Glibc broke backwards compatibility which I think they wouldn't want to do.
